- hosts: victim
  become: true
  become_user: root
  pre_tasks:
    - name: Install libselinux-python3
      dnf:
        name: libselinux-python3
        state: latest
  roles:
    - role: hostname
      vars:
        hostname: fedora
    - role: user
      vars:
        user_name: victim
        user_pwd: victim